### ISSUE TITLE
 Active record  version  error

### ISSUE THREAD

**Issue by gbs4ever** [learn-co-curriculum/activerecord-tvshow#32]
in this lab if we add the version it throws this error!  ,undefined method `[]' for #<ActiveRecord::Migration:0x00000002154698>  very confusing to us students when we need to or not to add please clarify ,  thanks

**Comment by maxwellbenton** [comment]
Hi @gbs4ever,

Thank you for spotting this and providing feedback. We've updated this lesson so that it works the same as labs around it, requiring a version for ActiveRecord migrations. We've updated the instructions as well, and believe this issue has been resolved.

Thank you for contributing to a Learn lesson!
